# Site settings
title: Ting ZHU
email: ting.zhu@warwick.ac.uk
description: > # this means to ignore newlines until "baseurl:"
  MSc in Statistics, University of Warwick
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  github_username

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 4
paginate_path: "/about/page:num/"


collections:
  about:
    output: true
    permalink: /about/:path/


